#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# add Anaconda 
export PATH="$HOME/Library/anaconda3/bin:$PATH"

# use vim as default editor
export VISUAL=vim
export EDITOR="$VISUAL"

# Customize to your needs...
# Source private info.
if [[ -s "$HOME/.private.zshrc" ]]; then
  source "$HOME/.private.zshrc"
fi

alias ctags="`brew --prefix`/bin/ctags"

alias ipynote="open -a Safari http://localhost:8888; jupyter notebook --no-browser"

alias mydnscrypt="sudo dnscrypt-proxy -R cisco --daemonize"

alias blogmod='date +"%Y-%m-%d %H:%M:%S" | xargs -I {} gsed -i "s/modify:.*/modify: {}/"'

alias mymkdir='pbpaste | sed "s/ /_/g" | xargs mkdir'
alias mvdespng='mv ~/Desktop/*.png'

## hadoop
alias hdfs="hadoop fs"

alias awklastcolumn='awk '\''{print $NF}'\'''

alias hdlsmore='hdfs -ls'

function hdls() {
    hdlsmore $1 | awklastcolumn;
}

alias hdtxtmore='hdfs -text'

function hdtxt() {
    if [ -z "$2" ]; then
        hdtxtmore $1 | head -n 5;
    else
        hdtxtmore $1 | head -n $2;
    fi
}
