#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh


# use vim as default editor
export VISUAL=vim
export EDITOR="$VISUAL"

# Customize to your needs...
# Source private info.
if [[ -s "$HOME/.private.zshrc.sh" ]]; then
  source "$HOME/.private.zshrc.sh"
fi

## alias
alias ctags="`brew --prefix`/bin/ctags"

alias ipynote="open -a Safari http://localhost:8888; jupyter notebook --no-browser"

alias mydnscrypt="sudo dnscrypt-proxy -R cisco --daemonize"

alias mymkdir='pbpaste | sed "s/ /_/g" | xargs mkdir'
alias mvdespng='mv ~/Desktop/*.png'

alias myvector='pbpaste | tr "," "\n" | nl'


# Hadoop
export JAVA_HOME="$(/usr/libexec/java_home)"

#Hadoop must be in your path for hive executable to work.
export HADOOP_HOME=/usr/local/Cellar/hadoop/hadoop
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

#After installation, set $HIVE_HOME in your profile:
export HIVE_HOME=/usr/local/Cellar/hive/hive-0.13.1
#If you want to use HCatalog with Pig, set $HCAT_HOME in your profile:
# export HCAT_HOME=/usr/local/Cellar/hive/1.2.1/libexec/hcatalog

# spark
export SPARK_HOME=/usr/local/Cellar/spark/spark


## function
alias hdfs="hadoop fs"

alias awklastcolumn='awk '\''{print $NF}'\'''

alias hdlsmore='hdfs -ls'

function hdls() {
    hdlsmore $1 | awklastcolumn;
}

alias hdtxtmore='hdfs -text'

function hdtxt() {
    if [ -z "$2" ]; then
        hdtxtmore $1 | head -n 5;
    else
        hdtxtmore $1 | head -n $2;
    fi
}

function blogmod() {
    TIME=`date +"%Y-%m-%d %H:%M:%S"`
    DAY=`date +"%Y-%m-%d"`

    gsed -i "s/^modify: .*/modify: $TIME/" $1
    gsed -i "s/^update: .*/update: $DAY/" $1
}


# git
alias mygitunmerge='git diff --diff-filter=U --name-only | xargs -o vim -p'


# Eclipse
export ECLIPSE_HOME=/Applications/Eclipse.app/Contents/Eclipse
alias myeclim="$ECLIPSE_HOME/eclimd"
alias myecliser="nohup $ECLIPSE_HOME/eclimd >> ~/.eclim/log 2>&1 &"


# Customize PATH
export PATH=${HADOOP_HOME}/bin:${SPARK_HOME}/bin:$HOME/Library/anaconda3/bin:$PATH
